// How big a city's download is (CR-03 Q5, 2026-09-09).
//
// `public/cities.json` is generated by `scripts/cities-manifest.mjs` from the
// artifacts in `web/public`; it maps the artifact path a city entry carries
// ("/graph-berlin.bin.gz") to the total bytes the browser fetches for it,
// parts summed. The registry (CLAUDE.md rule 2) stays a list of literals —
// this is the derived half, and it is regenerated rather than edited.
//
// Fetched ONCE, lazily, the first time the city sheet opens: a size the
// reader may never look at is not worth a request on boot, and nothing else
// in the app asks. A failure is not an error — the sheet simply shows the
// years without the megabytes, and the progress row counts against the
// response's own Content-Length instead.
import { coreUrls, isBanded, type City } from "./cities";

export type CityManifest = {
  /** artifact path -> bytes, parts summed. */
  bytes: Record<string, number>;
};

/** Parse whatever `/cities.json` answered with. Anything that is not the
 *  shape above — a 404 page, an old file, a hand-edit — reads as an empty
 *  manifest rather than throwing into the sheet. */
export function parseManifest(raw: unknown): CityManifest {
  const bytes: Record<string, number> = {};
  const src = (raw as { bytes?: unknown } | null)?.bytes;
  // an array would pass `typeof === "object"` and enumerate as {0: …, 1: …}
  if (src && typeof src === "object" && !Array.isArray(src)) {
    for (const [k, v] of Object.entries(src as Record<string, unknown>)) {
      if (typeof v === "number" && Number.isFinite(v) && v > 0) bytes[k] = v;
    }
  }
  return { bytes };
}

/** The download size of a city's artifact, or null when the manifest does
 *  not know it (no manifest, or a city whose artifact has not been synced
 *  into `public/` on the machine that generated it). */
export function artifactBytes(manifest: CityManifest | null, city: City): number | null {
  return manifest?.bytes[city.artifact] ?? null;
}

/** The bytes of the file the city sheet's Load button actually downloads:
 *  the whole artifact for a v7 city, the CORE for a v8 one (B11). It is the
 *  progress row's total, where `artifactBytes` above is the label — a v8
 *  city's core is about half of what the city costs in full, and counting
 *  a core download against the whole-city number would stall the bar at
 *  fifty per cent and then jump. Null when the manifest cannot say. */
export function coreBytes(manifest: CityManifest | null, city: City): number | null {
  if (!isBanded(city)) return artifactBytes(manifest, city);
  const key = coreUrls(city, "")[0].split("?")[0];
  return manifest?.bytes[key] ?? null;
}

/** Bytes as the sheet writes them: whole megabytes, decimal MB — the unit
 *  the boards use and the one a phone's own download UI uses. Never
 *  rounded to zero: a 400 KB artifact is "1 MB", not "0 MB". */
export function mb(bytes: number): number {
  return Math.max(1, Math.round(bytes / 1e6));
}

let pending: Promise<CityManifest | null> | null = null;

/** The manifest, fetched at most once per page. */
export function loadCityManifest(): Promise<CityManifest | null> {
  pending ??= fetch("/cities.json")
    .then((r) => (r.ok ? r.json() : null))
    .then((j) => (j === null ? null : parseManifest(j)))
    .catch(() => null);
  return pending;
}

/** For tests: forget the in-flight/cached fetch. */
export const __testing = {
  reset: () => {
    pending = null;
  },
};
